
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-hello-world
  namespace: default
  labels:
    app: nginx-hello-world
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-hello-world
  template:
    metadata:
      labels:
        app: nginx-hello-world
    spec:
      containers:
      - name: nginx
        image: nginxdemos/hello:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-hello-world-service
  namespace: default
  labels:
    app: nginx-hello-world
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx-hello-world
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-hello-world-config
  namespace: default
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>EKS Test Cluster - Hello World!</title>
        <style>
            body {
                font-family: Arial, sans-serif;
                background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                color: white;
                text-align: center;
                padding: 50px;
                margin: 0;
            }
            .container {
                background: rgba(255, 255, 255, 0.1);
                border-radius: 15px;
                padding: 40px;
                max-width: 600px;
                margin: 0 auto;
                backdrop-filter: blur(10px);
            }
            h1 { font-size: 3em; margin-bottom: 20px; }
            p { font-size: 1.2em; margin: 15px 0; }
            .info { background: rgba(255, 255, 255, 0.2); padding: 20px; border-radius: 10px; margin: 20px 0; }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>🎉 Hello from EKS!</h1>
            <p>Your cost-optimized EKS cluster is running successfully!</p>
            <div class="info">
                <p><strong>Cluster:</strong> eks-test-cluster</p>
                <p><strong>Instance Type:</strong> t3.small (SPOT)</p>
                <p><strong>Cost:</strong> ~$0.17/hour</p>
                <p><strong>Status:</strong> Ready for testing! ✅</p>
            </div>
            <p>This demo app is running on AWS EKS with:</p>
            <ul style="text-align: left; display: inline-block;">
                <li>2 nginx replicas for high availability</li>
                <li>Application Load Balancer for external access</li>
                <li>Resource limits for cost optimization</li>
                <li>Health checks for reliability</li>
            </ul>
        </div>
    </body>
    </html>
